version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.6.3-buster

commands:
  prepare:
    description: "Prepare to build/test image"
    steps:
      - checkout
      - run:
          name: Install pigz
          command: |
            set -x
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends pigz
      - setup_remote_docker
      - attach_workspace: { at: /tmp/workspace }
  build:
    description: "Build image"
    steps:
      - run:
          name: Load base image if necessary
          command: |
            set -x
            load_image=
            case "${CIRCLE_JOB}" in
              ruby|nodejs)                        load_image=baseimage;;
              ruby-full|rails5|tdiary)            load_image=ruby;;
              ruby-buster)                        load_image=baseimage-buster;;
              ruby-stretch)                       load_image=baseimage-stretch;;
            esac
            if [ -n "${load_image}" ]; then
              echo "Loading /tmp/${load_image}.tar.gz"
              ls -lah /tmp/workspace/
              pigz -c -d /tmp/workspace/${load_image}.tar.gz | docker load
            fi
      - run:
          name: Build image
          command: |
            set -x
            case "${CIRCLE_JOB}" in
              rspec-runner) docker build -t minimum2scp/rspec-runner:ci -f .circleci/rspec-runner/Dockerfile . 2>&1;;
              *)            docker build -t minimum2scp/${CIRCLE_JOB}:latest ${CIRCLE_JOB} 2>&1;;
            esac | tee /tmp/build.log
      - store_artifacts: { path: /tmp/build.log }
      - run:
          name: Save image if necessary
          command: |
            set -x
            case "${CIRCLE_JOB}" in
              rspec-runner)
                echo "Saving image minimum2scp/rspec-runner:ci to /tmp/rspec-runner.tar.gz"
                docker save minimum2scp/rspec-runner:ci | pigz -c - > /tmp/rspec-runner.tar.gz
                ;;
              baseimage|baseimage-*|ruby)
                echo "Saving image minimum2scp/${CIRCLE_JOB}:latest to /tmp/${CIRCLE_JOB}.tar.gz"
                docker save minimum2scp/${CIRCLE_JOB}:latest | pigz -c - > /tmp/${CIRCLE_JOB}.tar.gz
                ;;
              *)
                echo "Skipped to save image minimum2scp/${CIRCLE_JOB}:latest, creating /tmp/${CIRCLE_JOB}.tar.gz as empty file"
                : > /tmp/${CIRCLE_JOB}.tar.gz
                ;;
            esac
            ls -lh /tmp/${CIRCLE_JOB}.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths: [ "*.tar.gz" ]
  test:
    description: "Test image"
    steps:
      - run:
          name: Load rspec-runner image
          command: pigz -c -d /tmp/workspace/rspec-runner.tar.gz | docker load
      - run:
          name: Setup rspec-runner environment variables and volumes
          command: |
            set -x
            printenv | sort | grep -Ev '^(DOCKER_CERT_PATH|CIRCLE_BUILD_TOKEN)=' | grep -E '^(CI=|CIRCLECI=|CIRCLE_|DOCKER_)' > .circleci/env
            echo "DOCKER_CERT_PATH=/data/$(basename ${DOCKER_CERT_PATH})" >> .circleci/env
            docker volume create data
            docker create --name cfg -v data:/data minimum2scp/rspec-runner:ci
            docker cp ${DOCKER_CERT_PATH} cfg:/data
            docker rm cfg
      - run:
          name: Test image
          command: |
            docker run --rm -t --env-file .circleci/env -v data:/data minimum2scp/rspec-runner:ci \
            bundle exec rspec --color -f documentation -f RspecJunitFormatter -o /data/rspec.xml spec/${CIRCLE_JOB} \
            | tee /tmp/test.log
      - store_artifacts: { path: /tmp/test.log }
      - run:
          name: Download rspec.xml
          command: |
            mkdir /tmp/test-results
            docker create --name cfg -v data:/data minimum2scp/rspec-runner:ci
            docker cp cfg:/data/rspec.xml /tmp/test-results/rspec.xml
      # store_test_results is not supported with workflows (https://circleci.com/docs/2.0/configuration-reference/#store_test_results)
      - store_test_results: { path: /tmp/test-results }

jobs:
  rspec-runner:
    executor: my-executor
    steps: [ prepare, build ]
  baseimage:
    executor: my-executor
    steps: [ prepare, build, test ]
  nodejs:
    executor: my-executor
    steps: [ prepare, build, test ]
  ruby:
    executor: my-executor
    steps: [ prepare, build, test ]
  ruby-full:
    executor: my-executor
    steps: [ prepare, build, test ]
  rails5:
    executor: my-executor
    steps: [ prepare, build, test ]
  tdiary:
    executor: my-executor
    steps: [ prepare, build, test ]
  baseimage-buster:
    executor: my-executor
    steps: [ prepare, build, test ]
  ruby-buster:
    executor: my-executor
    steps: [ prepare, build, test ]
  baseimage-stretch:
    executor: my-executor
    steps: [ prepare, build, test ]
  ruby-stretch:
    executor: my-executor
    steps: [ prepare, build, test ]

workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec-runner
      - baseimage:
          requires: [rspec-runner]
      - nodejs:
          requires: [rspec-runner, baseimage]
      - ruby:
          requires: [rspec-runner, baseimage]
      - ruby-full:
          requires: [rspec-runner, ruby]
      - rails5:
          requires: [rspec-runner, ruby]
      - tdiary:
          requires: [rspec-runner, ruby]
      - baseimage-buster:
          requires: [rspec-runner]
      - ruby-buster:
          requires: [rspec-runner, baseimage-buster]
      - baseimage-stretch:
          requires: [rspec-runner]
      - ruby-stretch:
          requires: [rspec-runner, baseimage-stretch]

