name: Check upgradable packages

on:
  push:
    branches:
      - features/check-upgradable-packages-by-schedule

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - debian
          - baseimage
          - debian-buster
          - baseimage-buster
          - debian-stretch
          - baseimage-stretch
    steps:
      - name: Environment Variables
        run: export -p

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - uses: actions/checkout@master

      # setup ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem update --system -N
      - run: gem install bundler --version '>= 2.0.0' -N
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3

      # run test
      - run: docker pull minimum2scp/${{ matrix.image }}:latest
      - run: bundle exec rspec spec/${{ matrix.image }}/01apt_spec.rb

