name: Check upgradable packages

on:
  push:
    branches:
      - features/check-upgradable-packages-by-schedule

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - debian
          - baseimage
          - debian-buster
          - baseimage-buster
          - debian-stretch
          - baseimage-stretch
    steps:
      - uses: actions/checkout@master

      # setup ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem update --system -N
      - run: gem install bundler --version '>= 2.0.0' -N
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3

      # run test
      - run: bundle exec rspec spec/${{ matrix.image }}/01apt_spec.rb

