name: CI

on: [push]

jobs:
  rspec_runner:
    name: rspec-runner
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/checkout@master
      - run: docker build -t minimum2scp/rspec-runner:latest -f .circleci/rspec-runner/Dockerfile .
      - run: docker save minimum2scp/rspec-runner:latest | pigz -c - > /tmp/rspec-runner.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: rspec-runner
          path: /tmp/rspec-runner.tar.gz
  baseimage:
    name: baseimage
    runs-on: ubuntu-latest
    needs: [rspec_runner]
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/download-artifact@v1
        with:
          name: rspec-runner
          path: /tmp/rspec-runner
      - run: pigz -c -d /tmp/rspec-runner/rspec-runner.tar.gz | docker load
      - uses: actions/checkout@master
      - run: docker build -t minimum2scp/baseimage:latest baseimage
      - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock minimum2scp/rspec-runner:latest bundle exec rspec spec/baseimage
      - run: docker save minimum2scp/baseimage:latest | pigz -c - > /tmp/baseimage.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: baseimage
          path: /tmp/baseimage.tar.gz
  ruby:
    name: ruby
    runs-on: ubuntu-latest
    needs: [rspec_runner, baseimage]
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/download-artifact@v1
        with:
          name: rspec-runner
          path: /tmp/rspec-runner
      - run: pigz -c -d /tmp/rspec-runner/rspec-runner.tar.gz | docker load
      - uses: actions/download-artifact@v1
        with:
          name: baseimage
          path: /tmp/baseimage
      - run: pigz -c -d /tmp/baseimage/baseimage.tar.gz | docker load
      - uses: actions/checkout@master
      - run: docker build -t minimum2scp/ruby:latest ruby
      - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock minimum2scp/rspec-runner:latest bundle exec rspec spec/ruby

