name: CI

on: [push]

jobs:
  build_rspec_runner:
    name: build rspec-runner
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/checkout@master
      - run: docker build -t minimum2scp/rspec-runner:latest -f .circleci/rspec-runner/Dockerfile .
      - run: docker save minimum2scp/rspec-runner:latest | pigz -c - > /tmp/rspec-runner.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: rspec-runner
          path: /tmp/rspec-runner.tar.gz
  build_baseimage:
    name: build baseimage
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/checkout@master
      - run: docker build -t minimum2scp/baseimage:latest baseimage
      - run: docker save minimum2scp/baseimage:latest | pigz -c - > /tmp/baseimage.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: baseimage
          path: /tmp/baseimage.tar.gz
  test_baseimage:
    name: test baseimage
    runs-on: ubuntu-latest
    needs: [build_rspec_runner, build_baseimage]
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/download-artifact@v1
        with:
          name: rspec-runner
          path: /tmp
      - run: pigz -c -d /tmp/rspec-runner.tar.gz | docker load
      - uses: actions/download-artifact@v1
        with:
          name: baseimage
          path: /tmp
      - run: pigz -c -d /tmp/baseimage.tar.gz | docker load
      - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock minimum2scp/rspec-runner:latest bundle exec rspec spec/baseimage
  build_ruby:
    name: build ruby
    runs-on: ubuntu-latest
    needs: [build_baseimage]
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/download-artifact@v1
        with:
          name: baseimage
          path: /tmp
      - run: pigz -c -d /tmp/baseimage.tar.gz | docker load
      - uses: actions/checkout@master
      - run: docker build -t minimum2scp/ruby:latest ruby
      - run: docker save minimum2scp/ruby:latest | pigz -c - > /tmp/ruby.tar.gz
      - uses: actions/upload-artifact@v1
        with:
          name: ruby
          path: /tmp/ruby.tar.gz
  test_ruby:
    name: test ruby
    runs-on: ubuntu-latest
    needs: [build_rspec_runner, build_ruby]
    steps:
      - shell: bash
        name: Install pigz
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pigz
      - uses: actions/download-artifact@v1
        with:
          name: rspec-runner
          path: /tmp
      - run: pigz -c -d /tmp/rspec-runner.tar.gz | docker load
      - uses: actions/download-artifact@v1
        with:
          name: ruby
          path: /tmp
      - run: pigz -c -d /tmp/ruby.tar.gz | docker load
      - run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock minimum2scp/rspec-runner:latest bundle exec rspec spec/ruby

